create schema ativ_fixacao;

use ativ_fixacao;

#TABELAS SEM CHAVE ESTRANGEIRAS
create table if not exists locais(
ID_LOCAIS INT PRIMARY KEY,
NOME_LOCAIS VARCHAR(100) NOT NULL,
LOG_LOCAL VARCHAR(100) NOT NULL,
NUMLOG_LOCAL INT,
BAIRRO_LOCAL VARCHAR(100) NOT NULL,
CIDADE VARCHAR(100) NOT NULL,
UF CHAR(2) NOT NULL,
CEP VARCHAR(20) NOT NULL,
CAPACIDADE INT NOT NULL
);

create table if not exists participantes(
PARTNUM_INSCRICAO INT NOT NULL,
PARTCPF VARCHAR(20) NOT NULL,
PRIMARY KEY (PARTNUM_INSCRICAO, PARTCPF),
NOME_PART VARCHAR(100) NOT NULL,
DATA_NASC DATE,
EMPRESA VARCHAR(100)
);

#TABELAS COM CHAVES ESTRANGEIRAS
create table if not exists atividades(
ID_ATIVIDADE INT PRIMARY KEY,
NOME_ATV VARCHAR(100) NOT NULL,
DATA_ATV DATE NOT NULL,
HORA_ATV TIME NOT NULL,
EVENTO_ATV INT NOT NULL,
CONSTRAINT FK_eventos FOREIGN KEY(EVENTO_ATV) REFERENCES eventos(ID_EVENTO)
);

create table if not exists eventos(
ID_EVENTO INT PRIMARY KEY,
NOME_EVENTO VARCHAR(100) NOT NULL,
DATA_EVENTO DATE NOT NULL,
ENTIDADE_EVENTO VARCHAR(100) NOT NULL,
LOCAL_EVENTO INT,
CONSTRAINT FK_locais FOREIGN KEY(LOCAL_EVENTO) REFERENCES locais(ID_LOCAIS)
);




